### ISSUE TITLE
UITabBarController In Desktop&Android

### ISSUE THREAD

**Issue by moazzin** [crossmob/CrossMobile#3]
when i use UITabBarController, i face with "crossmobile.ios.uikit.UIResponder is abstract; cannot be instantiated" error in desktop, android running , but there is no any problem in ios running

**Comment by teras** [comment]
Hello moazzin.
How did you initialize UITabBarController?

Could you give more information?
UITabBarController is not abstract and can be created, on both platforms.

**Comment by moazzin** [comment]
I Just use Storyboard &
I push the code here :
https://github.com/moazzin/cm_first

**Comment by moazzin** [comment]
<img width="1680" alt="Screen Shot 1399-08-19 at 21 44 54" src="https://user-images.githubusercontent.com/3841134/98580249-eaa49d80-22d4-11eb-8df6-49fa8fc8eabb.png">

**_some times it run with this face_**

<img width="1680" alt="Screen Shot 1399-08-19 at 22 58 42" src="https://user-images.githubusercontent.com/3841134/98587341-41af7000-22df-11eb-8769-f67bdc9f6dd4.png">

**_and some times i got this error_**

> Launch desktop target

Listening for transport dt_socket at address: 50781
Error stacktraces are turned on.
Scanning for projects...

------------------------------------------------------------------------
Building Tools 1.0.0.0
------------------------------------------------------------------------

--- cmbuild-maven-plugin:3.3.0:resources (default) @ tools ---
State: unknown attribute catalog
Color: unknown attribute systemColor
State: unknown attribute catalog
Color: unknown attribute systemColor
Color: unknown attribute systemColor
Color: unknown attribute systemColor
Color: unknown attribute systemColor
State: unknown attribute catalog
Color: unknown attribute systemColor
State: unknown attribute catalog
State: unknown attribute catalog
BarButtonItem: unknown attribute catalog
NavigationItem: key titleView of type segmentedControl not compatible with org.crossmobile.build.ib.visual.View@acdcf71
TabBarController: unsupported key tabBar of type tabBar
NavigationController: unknown attribute automaticallyAdjustsScrollViewInsets
NavigationController: unsupported key tabBarItem of type tabBarItem
NavigationController: Missing toolbarItems element
NavigationController: unknown attribute automaticallyAdjustsScrollViewInsets
NavigationController: unsupported key tabBarItem of type tabBarItem
NavigationController: Missing toolbarItems element
Added 11 Interface Builder resource classes
Writing CrossMobile properties files
Writing Info.plist file for application tools

--- maven-compiler-plugin:3.1:compile (default-compile) @ tools ---
Changes detected - recompiling the module!
Compiling 5 source files to /Users/taha/Projects/CrossMobile/tools/target/classes
-------------------------------------------------------------
COMPILATION ERROR : 
-------------------------------------------------------------
/Users/taha/Projects/CrossMobile/tools/target/generated-sources/main/org/crossmobile/sys/IBObjects.java:[119,21] crossmobile.ios.uikit.UIResponder is abstract; cannot be instantiated
/Users/taha/Projects/CrossMobile/tools/target/generated-sources/main/org/crossmobile/sys/IBObjects.java:[153,45] cannot find symbol
  symbol:   method white()
  location: class crossmobile.ios.uikit.UIColor
/Users/taha/Projects/CrossMobile/tools/target/generated-sources/main/org/crossmobile/sys/IBObjects.java:[209,40] cannot find symbol
  symbol:   method white()
  location: class crossmobile.ios.uikit.UIColor
/Users/taha/Projects/CrossMobile/tools/target/generated-sources/main/org/crossmobile/sys/IBObjects.java:[224,40] cannot find symbol
  symbol:   method white()
  location: class crossmobile.ios.uikit.UIColor
/Users/taha/Projects/CrossMobile/tools/target/generated-sources/main/org/crossmobile/sys/IBObjects.java:[275,21] crossmobile.ios.uikit.UIResponder is abstract; cannot be instantiated
/Users/taha/Projects/CrossMobile/tools/target/generated-sources/main/org/crossmobile/sys/IBObjects.java:[314,45] cannot find symbol
  symbol:   method white()
  location: class crossmobile.ios.uikit.UIColor
/Users/taha/Projects/CrossMobile/tools/target/generated-sources/main/org/crossmobile/sys/IBObjects.java:[388,39] cannot find symbol
  symbol:   method white()
  location: class crossmobile.ios.uikit.UIColor
/Users/taha/Projects/CrossMobile/tools/target/generated-sources/main/org/crossmobile/sys/IBObjects.java:[403,39] cannot find symbol
  symbol:   method white()
  location: class crossmobile.ios.uikit.UIColor
/Users/taha/Projects/CrossMobile/tools/target/generated-sources/main/org/crossmobile/sys/IBObjects.java:[485,21] crossmobile.ios.uikit.UIResponder is abstract; cannot be instantiated
/Users/taha/Projects/CrossMobile/tools/target/generated-sources/main/org/crossmobile/sys/IBObjects.java:[506,21] crossmobile.ios.uikit.UIResponder is abstract; cannot be instantiated
/Users/taha/Projects/CrossMobile/tools/target/generated-sources/main/org/crossmobile/sys/IBObjects.java:[541,21] crossmobile.ios.uikit.UIResponder is abstract; cannot be instantiated
11 errors 
-------------------------------------------------------------
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 2.203 s
Finished at: 2020-11-09T22:48:34+03:30
Final Memory: 17M/189M
------------------------------------------------------------------------
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project tools: Compilation failure: Compilation failure: 
/Users/taha/Projects/CrossMobile/tools/target/generated-sources/main/org/crossmobile/sys/IBObjects.java:[119,21] crossmobile.ios.uikit.UIResponder is abstract; cannot be instantiated
/Users/taha/Projects/CrossMobile/tools/target/generated-sources/main/org/crossmobile/sys/IBObjects.java:[153,45] cannot find symbol
  symbol:   method white()
  location: class crossmobile.ios.uikit.UIColor
/Users/taha/Projects/CrossMobile/tools/target/generated-sources/main/org/crossmobile/sys/IBObjects.java:[209,40] cannot find symbol
  symbol:   method white()
  location: class crossmobile.ios.uikit.UIColor
/Users/taha/Projects/CrossMobile/tools/target/generated-sources/main/org/crossmobile/sys/IBObjects.java:[224,40] cannot find symbol
  symbol:   method white()
  location: class crossmobile.ios.uikit.UIColor
/Users/taha/Projects/CrossMobile/tools/target/generated-sources/main/org/crossmobile/sys/IBObjects.java:[275,21] crossmobile.ios.uikit.UIResponder is abstract; cannot be instantiated
/Users/taha/Projects/CrossMobile/tools/target/generated-sources/main/org/crossmobile/sys/IBObjects.java:[314,45] cannot find symbol
  symbol:   method white()
  location: class crossmobile.ios.uikit.UIColor
/Users/taha/Projects/CrossMobile/tools/target/generated-sources/main/org/crossmobile/sys/IBObjects.java:[388,39] cannot find symbol
  symbol:   method white()
  location: class crossmobile.ios.uikit.UIColor
/Users/taha/Projects/CrossMobile/tools/target/generated-sources/main/org/crossmobile/sys/IBObjects.java:[403,39] cannot find symbol
  symbol:   method white()
  location: class crossmobile.ios.uikit.UIColor
/Users/taha/Projects/CrossMobile/tools/target/generated-sources/main/org/crossmobile/sys/IBObjects.java:[485,21] crossmobile.ios.uikit.UIResponder is abstract; cannot be instantiated
/Users/taha/Projects/CrossMobile/tools/target/generated-sources/main/org/crossmobile/sys/IBObjects.java:[506,21] crossmobile.ios.uikit.UIResponder is abstract; cannot be instantiated
/Users/taha/Projects/CrossMobile/tools/target/generated-sources/main/org/crossmobile/sys/IBObjects.java:[541,21] crossmobile.ios.uikit.UIResponder is abstract; cannot be instantiated
-> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project tools: Compilation failure
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:858)
	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more

Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by teras** [comment]
Thank you for the thorough bug report.
Indeed there's a problem.
We are looking at it.

Just a note though: the new iOS 14 icons are not supported yet...

**Comment by teras** [comment]
Current Git repository is able to load the IB file. It's still missing a few bits.
If you are still interested, we can pack a version and let you check it.
